/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/82jEvbKuCCq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"

export function GlossartBanner2() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r">
      <div className="container px-4 md:px-6 flex flex-col items-center text-center">
        <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white">
          Bitcoin Glossary
        </h1>
        <div className="mt-6 w-full max-w-md">
          <div className="relative">
            <SearchIcon className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500" />
            <Input
              className="pl-12 pr-4 py-3 rounded-full bg-white shadow-lg focus:outline-none focus:ring-2 focus:ring-[#fff] focus:border-transparent"
              placeholder="Search the glossary..."
              type="text"
            />
          </div>
        </div>
      </div>
    </section>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
