/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xoLjGe0uN8N
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function GlossaryBanner() {
  return (
    <main className="flex flex-col items-center justify-center h-screen bg-gradient-to-r from-[#f7931a] to-[#e48600] px-4 md:px-6">
      <div className="max-w-3xl w-full space-y-8">
        <h1 className="text-5xl md:text-7xl font-bold text-white">Bitcoin Glossary</h1>
        <div className="relative w-full">
          <Input
            className="w-full rounded-full bg-white/90 px-6 py-4 text-lg focus:outline-none focus:ring-2 focus:ring-[#f7931a]"
            placeholder="Search the Bitcoin Glossary"
            type="text"
          />
          <Button
            className="absolute top-1/2 right-4 -translate-y-1/2 text-[#f7931a] hover:text-[#e48600] focus:outline-none focus:ring-2 focus:ring-[#f7931a]"
            type="submit"
            variant="ghost"
          >
            <SearchIcon className="h-6 w-6" />
          </Button>
        </div>
        <p className="text-2xl md:text-3xl font-medium text-white">Unlock the Crypto Lexicon</p>
      </div>
    </main>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
