/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/quohR2WS2JG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Button } from "./ui/button"

export default function NextPrevious({ nextTopic, previousTopic }) {
  return (
    <div className="flex justify-between">
      <Button className="bg-[#E0E0E0] text-black px-6 py-2 rounded-full flex items-center">
      <span className="text-xs">Previous</span>
        <ChevronLeftIcon className="mr-2" />
        <span className="truncate mx-1">{previousTopic}</span>
      </Button>
      <Button className="bg-[#FFA500] text-white px-6 py-2 rounded-full flex items-center">
        <span className="truncate mx-1">{nextTopic}</span>
        <ChevronRightIcon className="ml-2" />
        <span className="text-xs">Next</span>
      </Button>
    </div>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
